name: global
type: namespace

networks:
  - name: docs-next-hat

clusters:
  - name: docs-next-hat
    auto_start: true
    proxy_templates:
      - docs-next-hat
    vars:
      DOMAIN: docsv2.next-hat.com
    joins:
      - cargo: docs-next-hat
        network: docs-next-hat

cargoes:
  - name: docs-next-hat
    image: docs-next-hat:master
