# Publish to docs.next-hat.com

name: Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client

      - name: Deploy
        env:
          USER: ${{ secrets.DEPLOY_USER }}
          PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        run: |
          mkdir /home/runner/.ssh
          ssh-keygen -R 164.132.172.153
          sshpass -p "$PASSWORD" scp -r . $USER@164.132.172.153:/opt/next-hat-doc
