# Publish to docs.next-hat.com

name: Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass openssh-client

      - name: Deploy
        env:
          SSHPASS: ${{ secrets.DEPLOY_PASSWORD }}
          USER: ${{ secrets.DEPLOY_USER }}
        run: |
          sshpass -e ssh next-hat-doc@164.132.172.153 ls
